import { boolean, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: "string" });

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  avatarUrl: text("avatar_url"),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const workspaces = pgTable("workspaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  policyJson: jsonb("policy_json").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const memberships = pgTable("memberships", {
  workspaceId: text("workspace_id").notNull(),
  userId: text("user_id").notNull(),
  role: text("role").notNull(),
  status: text("status").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const authSessions = pgTable("auth_sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  secretHash: text("secret_hash").notNull(),
  expiresAt: timestamptz("expires_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
  createdAt: timestamptz("created_at").notNull(),
  lastSeenAt: timestamptz("last_seen_at").notNull(),
});

export const agentProfiles = pgTable("agent_profiles", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  handle: text("handle").notNull(),
  name: text("name").notNull(),
  title: text("title").notNull(),
  avatarSeed: text("avatar_seed"),
  visibility: text("visibility").notNull(),
  status: text("status").notNull(),
  editableConfigJson: jsonb("editable_config_json").notNull(),
  currentVersionId: text("current_version_id"),
  configRevision: integer("config_revision").notNull(),
  nativeSubagentsEnabled: boolean("native_subagents_enabled").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const agentVersions = pgTable("agent_versions", {
  id: text("id").primaryKey(),
  agentProfileId: text("agent_profile_id").notNull(),
  version: integer("version").notNull(),
  configJson: jsonb("config_json").notNull(),
  specHash: text("spec_hash").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const coworkerDrafts = pgTable("coworker_drafts", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  sourceTextEncrypted: text("source_text_encrypted").notNull(),
  proposalJson: jsonb("proposal_json").notNull(),
  effectivePreviewJson: jsonb("effective_preview_json").notNull(),
  draftHash: text("draft_hash").notNull(),
  revision: integer("revision").notNull(),
  policyRevision: integer("policy_revision").notNull(),
  catalogRevision: integer("catalog_revision").notNull(),
  state: text("state").notNull(),
  createdBy: text("created_by").notNull(),
  expiresAt: timestamptz("expires_at").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  decidedAt: timestamptz("decided_at"),
});

export const sessionRevisions = pgTable("session_revisions", {
  id: text("id").primaryKey(),
  agentProfileId: text("agent_profile_id").notNull(),
  sourceConfigRevision: integer("source_config_revision").notNull(),
  effectiveConfigRedactedJson: jsonb("effective_config_redacted_json").notNull(),
  effectiveSpecHash: text("effective_spec_hash").notNull(),
  approvalPolicyHash: text("approval_policy_hash").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const skills = pgTable("skills", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  stableName: text("stable_name").notNull(),
  displayName: text("display_name").notNull(),
  ownerUserId: text("owner_user_id").notNull(),
  visibility: text("visibility").notNull(),
  status: text("status").notNull(),
  currentVersionId: text("current_version_id"),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const skillVersions = pgTable("skill_versions", {
  id: text("id").primaryKey(),
  skillId: text("skill_id").notNull(),
  version: integer("version").notNull(),
  state: text("state").notNull(),
  manifestJson: jsonb("manifest_json").notNull(),
  manifestHash: text("manifest_hash").notNull(),
  skillMarkdownBlobKey: text("skill_markdown_blob_key").notNull(),
  contentHash: text("content_hash").notNull(),
  sourceRunId: text("source_run_id"),
  sourceStepIdsJson: jsonb("source_step_ids_json").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  publishedAt: timestamptz("published_at"),
  revokedAt: timestamptz("revoked_at"),
});

export const agentSkillBindings = pgTable("agent_skill_bindings", {
  id: text("id").primaryKey(),
  agentProfileId: text("agent_profile_id").notNull(),
  agentVersionId: text("agent_version_id").notNull(),
  skillVersionId: text("skill_version_id").notNull(),
  state: text("state").notNull(),
  attachedBy: text("attached_by").notNull(),
  attachedAt: timestamptz("attached_at").notNull(),
  detachedAt: timestamptz("detached_at"),
});

export const channels = pgTable("channels", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  name: text("name").notNull(),
  missionBrief: text("mission_brief").notNull(),
  summary: text("summary"),
  policyJson: jsonb("policy_json").notNull(),
  nextSequence: integer("next_sequence").notNull(),
  status: text("status").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const channelParticipants = pgTable("channel_participants", {
  channelId: text("channel_id").notNull(),
  participantType: text("participant_type").notNull(),
  participantId: text("participant_id").notNull(),
  role: text("role").notNull(),
  joinedAt: timestamptz("joined_at").notNull(),
  removedAt: timestamptz("removed_at"),
});

export const channelEvents = pgTable("channel_events", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").notNull(),
  sequence: integer("sequence").notNull(),
  type: text("type").notNull(),
  actorType: text("actor_type").notNull(),
  actorId: text("actor_id").notNull(),
  runId: text("run_id"),
  payloadJson: jsonb("payload_json").notNull(),
  aguiEventType: text("agui_event_type"),
  aguiEventJson: jsonb("agui_event_json"),
  logicalThreadId: text("logical_thread_id"),
  createdAt: timestamptz("created_at").notNull(),
});

export const messages = pgTable("messages", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").notNull(),
  eventId: text("event_id").notNull(),
  authorType: text("author_type").notNull(),
  authorId: text("author_id").notNull(),
  body: text("body").notNull(),
  parentMessageId: text("parent_message_id"),
  createdAt: timestamptz("created_at").notNull(),
});

export const channelPins = pgTable("channel_pins", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").notNull(),
  sourceEventId: text("source_event_id"),
  sourceArtifactId: text("source_artifact_id"),
  label: text("label").notNull(),
  pinnedBy: text("pinned_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  removedAt: timestamptz("removed_at"),
});

export const tasks = pgTable("tasks", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  status: text("status").notNull(),
  assigneeType: text("assignee_type"),
  assigneeId: text("assignee_id"),
  sourceMessageId: text("source_message_id"),
  sourceRunId: text("source_run_id"),
  dueAt: timestamptz("due_at"),
  currentRevision: integer("current_revision").notNull(),
  createdByType: text("created_by_type").notNull(),
  createdById: text("created_by_id").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const taskRevisions = pgTable("task_revisions", {
  id: text("id").primaryKey(),
  taskId: text("task_id").notNull(),
  revision: integer("revision").notNull(),
  dataJson: jsonb("data_json").notNull(),
  dataHash: text("data_hash").notNull(),
  changedFieldsJson: jsonb("changed_fields_json").notNull(),
  sourceManifestJson: jsonb("source_manifest_json"),
  sourceManifestHash: text("source_manifest_hash"),
  actorType: text("actor_type").notNull(),
  actorId: text("actor_id").notNull(),
  commandId: text("command_id").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const taskGrants = pgTable("task_grants", {
  id: text("id").primaryKey(),
  taskId: text("task_id"),
  channelId: text("channel_id").notNull(),
  subjectType: text("subject_type").notNull(),
  subjectId: text("subject_id").notNull(),
  allowedOperationsJson: jsonb("allowed_operations_json").notNull(),
  allowedFieldsJson: jsonb("allowed_fields_json").notNull(),
  allowedTransitionsJson: jsonb("allowed_transitions_json").notNull(),
  policyRevision: integer("policy_revision").notNull(),
  grantedBy: text("granted_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
});

export const workspaceCommandReceipts = pgTable("workspace_command_receipts", {
  workspaceId: text("workspace_id").notNull(),
  commandKind: text("command_kind").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  resultId: text("result_id").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const channelAgentSessions = pgTable("channel_agent_sessions", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  logicalAguiThreadId: text("logical_agui_thread_id").notNull(),
  currentGenerationId: text("current_generation_id"),
  lastDeliveredChannelSequence: integer("last_delivered_channel_sequence").notNull(),
  state: text("state").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const channelAgentSessionGenerations = pgTable("channel_agent_session_generations", {
  id: text("id").primaryKey(),
  channelAgentSessionId: text("channel_agent_session_id").notNull(),
  generation: integer("generation").notNull(),
  agentVersionId: text("agent_version_id"),
  sessionRevisionId: text("session_revision_id").notNull(),
  trueforgeSessionId: text("trueforge_session_id").notNull(),
  effectiveSpecHash: text("effective_spec_hash").notNull(),
  approvalPolicyHash: text("approval_policy_hash").notNull(),
  activeTurnId: text("active_turn_id"),
  state: text("state").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  retiredAt: timestamptz("retired_at"),
});

export const runs = pgTable("runs", {
  id: text("id").primaryKey(),
  channelId: text("channel_id").notNull(),
  sourceMessageId: text("source_message_id").notNull(),
  requestedBy: text("requested_by").notNull(),
  routingMode: text("routing_mode").notNull(),
  goal: text("goal").notNull(),
  lifecycle: text("lifecycle").notNull(),
  schedulingPaused: boolean("scheduling_paused").notNull(),
  budgetJson: jsonb("budget_json").notNull(),
  startedAt: timestamptz("started_at"),
  completedAt: timestamptz("completed_at"),
});

export const runSteps = pgTable("run_steps", {
  id: text("id").primaryKey(),
  runId: text("run_id").notNull(),
  assignedAgentId: text("assigned_agent_id").notNull(),
  objective: text("objective").notNull(),
  expectedOutput: text("expected_output"),
  contextRefsJson: jsonb("context_refs_json").notNull(),
  state: text("state").notNull(),
  attempt: integer("attempt").notNull(),
  startedAt: timestamptz("started_at"),
  completedAt: timestamptz("completed_at"),
});

export const turnQueueItems = pgTable("turn_queue_items", {
  id: text("id").primaryKey(),
  channelAgentSessionId: text("channel_agent_session_id").notNull(),
  runStepId: text("run_step_id").notNull(),
  boundSessionGenerationId: text("bound_session_generation_id"),
  inputType: text("input_type").notNull(),
  inputPayloadRedactedJson: jsonb("input_payload_redacted_json").notNull(),
  priority: integer("priority").notNull(),
  fifoSequence: integer("fifo_sequence").notNull(),
  state: text("state").notNull(),
  leaseOwner: text("lease_owner"),
  leaseExpiresAt: timestamptz("lease_expires_at"),
  createdAt: timestamptz("created_at").notNull(),
  claimedAt: timestamptz("claimed_at"),
  completedAt: timestamptz("completed_at"),
});

export const agentTurns = pgTable("agent_turns", {
  id: text("id").primaryKey(),
  runStepId: text("run_step_id").notNull(),
  channelAgentSessionId: text("channel_agent_session_id").notNull(),
  sessionGenerationId: text("session_generation_id").notNull(),
  queueItemId: text("queue_item_id").notNull(),
  applicationRunToken: text("application_run_token").notNull(),
  trueforgeTurnId: text("trueforge_turn_id"),
  aguiRunId: text("agui_run_id").notNull(),
  previousTrueforgeTurnId: text("previous_trueforge_turn_id"),
  inputType: text("input_type").notNull(),
  lastTrueforgeSequence: integer("last_trueforge_sequence").notNull(),
  contextThroughChannelSequence: integer("context_through_channel_sequence").notNull(),
  state: text("state").notNull(),
  errorJson: jsonb("error_json"),
  startedAt: timestamptz("started_at"),
  completedAt: timestamptz("completed_at"),
});

export const runEvents = pgTable("run_events", {
  id: text("id").primaryKey(),
  agentTurnId: text("agent_turn_id").notNull(),
  trueforgeEventId: text("trueforge_event_id").notNull(),
  threadId: text("thread_id"),
  normalizedPayloadRedactedJson: jsonb("normalized_payload_redacted_json").notNull(),
  normalizedType: text("normalized_type").notNull(),
  firstSeenAt: timestamptz("first_seen_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const aguiEventRecords = pgTable("agui_event_records", {
  id: text("id").primaryKey(),
  channelEventId: text("channel_event_id").notNull(),
  agentTurnId: text("agent_turn_id"),
  logicalThreadId: text("logical_thread_id"),
  aguiRunId: text("agui_run_id"),
  eventType: text("event_type").notNull(),
  messageOrActivityId: text("message_or_activity_id"),
  storageKind: text("storage_kind").notNull(),
  eventJson: jsonb("event_json"),
  schemaProfile: text("schema_profile").notNull(),
  eventHash: text("event_hash").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const connectorBindings = pgTable("connector_bindings", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  provider: text("provider").notNull(),
  credentialOwnerType: text("credential_owner_type").notNull(),
  credentialOwnerId: text("credential_owner_id").notNull(),
  composioUserId: text("composio_user_id"),
  composioSessionId: text("composio_session_id"),
  trueforgeConnectorName: text("trueforge_connector_name").notNull(),
  configVersion: integer("config_version").notNull(),
  configHash: text("config_hash").notNull(),
  allowedToolsJson: jsonb("allowed_tools_json").notNull(),
  actingIdentityJson: jsonb("acting_identity_json").notNull(),
  status: text("status").notNull(),
  verifiedAt: timestamptz("verified_at"),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const toolGrants = pgTable("tool_grants", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  connectorBindingId: text("connector_binding_id").notNull(),
  toolName: text("tool_name").notNull(),
  classification: text("classification").notNull(),
  approvalPolicy: text("approval_policy").notNull(),
  observedDescriptorHash: text("observed_descriptor_hash").notNull(),
  toolPolicyKey: text("tool_policy_key").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
});

export const uiComponents = pgTable("ui_components", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  stableName: text("stable_name").notNull(),
  kind: text("kind").notNull(),
  currentPublishedVersionId: text("current_published_version_id"),
  status: text("status").notNull(),
  createdBy: text("created_by").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
});

export const uiComponentVersions = pgTable("ui_component_versions", {
  id: text("id").primaryKey(),
  componentId: text("component_id").notNull(),
  semanticVersion: text("semantic_version").notNull(),
  exposure: text("exposure").notNull(),
  confirmationPolicy: text("confirmation_policy").notNull(),
  modelDescription: text("model_description").notNull(),
  argumentSchemaJson: jsonb("argument_schema_json").notNull(),
  rendererKey: text("renderer_key").notNull(),
  previewPropsJson: jsonb("preview_props_json").notNull(),
  declaredDataFunctionsJson: jsonb("declared_data_functions_json").notNull(),
  declaredInteractionIntentsJson: jsonb("declared_interaction_intents_json").notNull(),
  descriptorHash: text("descriptor_hash").notNull(),
  publishedBy: text("published_by").notNull(),
  publishedAt: timestamptz("published_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
});

export const uiComponentGrants = pgTable("ui_component_grants", {
  id: text("id").primaryKey(),
  componentVersionId: text("component_version_id").notNull(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id"),
  agentProfileId: text("agent_profile_id"),
  grantedBy: text("granted_by").notNull(),
  grantedAt: timestamptz("granted_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
});

export const uiDataFunctionGrants = pgTable("ui_data_function_grants", {
  id: text("id").primaryKey(),
  componentVersionId: text("component_version_id").notNull(),
  functionName: text("function_name").notNull(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id"),
  agentProfileId: text("agent_profile_id"),
  limitsJson: jsonb("limits_json").notNull(),
  grantedBy: text("granted_by").notNull(),
  grantedAt: timestamptz("granted_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
});

export const uiInstances = pgTable("ui_instances", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id").notNull(),
  runId: text("run_id").notNull(),
  runStepId: text("run_step_id").notNull(),
  agentTurnId: text("agent_turn_id").notNull(),
  logicalThreadId: text("logical_thread_id").notNull(),
  toolCallId: text("tool_call_id").notNull(),
  componentVersionId: text("component_version_id").notNull(),
  activityMessageId: text("activity_message_id").notNull(),
  sourceEventId: text("source_event_id").notNull(),
  creatorAgentId: text("creator_agent_id").notNull(),
  title: text("title").notNull(),
  renderGrantId: text("render_grant_id"),
  replacesUiInstanceId: text("replaces_ui_instance_id"),
  currentRenderRevision: integer("current_render_revision"),
  lastGoodRenderRevision: integer("last_good_render_revision"),
  currentStateRevision: integer("current_state_revision"),
  textAlternative: text("text_alternative").notNull(),
  status: text("status").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  updatedAt: timestamptz("updated_at").notNull(),
  readyAt: timestamptz("ready_at"),
  quarantinedAt: timestamptz("quarantined_at"),
});

export const uiInstanceRevisions = pgTable("ui_instance_revisions", {
  id: text("id").primaryKey(),
  uiInstanceId: text("ui_instance_id").notNull(),
  revisionKind: text("revision_kind").notNull(),
  revision: integer("revision").notNull(),
  baseRevision: integer("base_revision"),
  componentVersionId: text("component_version_id"),
  rendererVersion: text("renderer_version"),
  rendererProfileHash: text("renderer_profile_hash"),
  validatorPolicyVersion: text("validator_policy_version").notNull(),
  argumentSchemaJson: jsonb("argument_schema_json"),
  argumentSchemaHash: text("argument_schema_hash"),
  stateSchemaJson: jsonb("state_schema_json"),
  stateSchemaHash: text("state_schema_hash"),
  interactionManifestJson: jsonb("interaction_manifest_json"),
  interactionManifestHash: text("interaction_manifest_hash"),
  dataBindingManifestJson: jsonb("data_binding_manifest_json"),
  dataBindingManifestHash: text("data_binding_manifest_hash"),
  renderNodeSetJson: jsonb("render_node_set_json"),
  renderNodeSetHash: text("render_node_set_hash"),
  renderPayloadJson: jsonb("render_payload_json"),
  renderPayloadHash: text("render_payload_hash"),
  renderManifestJson: jsonb("render_manifest_json"),
  manifestHash: text("manifest_hash"),
  validatedPropsJson: jsonb("validated_props_json"),
  validatedPropsHash: text("validated_props_hash"),
  scopedStateJson: jsonb("scoped_state_json"),
  scopedStateHash: text("scoped_state_hash"),
  activitySnapshotJson: jsonb("activity_snapshot_json"),
  dataSnapshotJson: jsonb("data_snapshot_json"),
  dataSnapshotHash: text("data_snapshot_hash"),
  accessibleSummary: text("accessible_summary"),
  contentHash: text("content_hash").notNull(),
  validationState: text("validation_state").notNull(),
  createdAt: timestamptz("created_at").notNull(),
  promotedAt: timestamptz("promoted_at"),
});

export const uiSurfaceGrants = pgTable("ui_surface_grants", {
  id: text("id").primaryKey(),
  uiInstanceId: text("ui_instance_id").notNull(),
  grantKind: text("grant_kind").notNull(),
  policyRevision: integer("policy_revision").notNull(),
  boundRenderRevision: integer("bound_render_revision"),
  boundManifestHash: text("bound_manifest_hash"),
  rail: text("rail"),
  allowedComponentTypesJson: jsonb("allowed_component_types_json"),
  limitsJson: jsonb("limits_json"),
  dataRef: text("data_ref"),
  allowedFieldPathsJson: jsonb("allowed_field_paths_json"),
  maxRows: integer("max_rows"),
  maxBytes: integer("max_bytes"),
  snapshotSchemaHash: text("snapshot_schema_hash"),
  immutableSnapshotHash: text("immutable_snapshot_hash"),
  actionRef: text("action_ref"),
  handlerKey: text("handler_key"),
  actionMode: text("action_mode"),
  inputSchemaJson: jsonb("input_schema_json"),
  inputSchemaHash: text("input_schema_hash"),
  allowedRenderNodeIdsJson: jsonb("allowed_render_node_ids_json"),
  linkedDataGrantId: text("linked_data_grant_id"),
  componentInterruptId: text("component_interrupt_id"),
  grantBodyRedactedJson: jsonb("grant_body_redacted_json").notNull(),
  grantScopeHash: text("grant_scope_hash").notNull(),
  maxUses: integer("max_uses"),
  useCount: integer("use_count").notNull(),
  issuedBy: text("issued_by").notNull(),
  expiresAt: timestamptz("expires_at").notNull(),
  revokedAt: timestamptz("revoked_at"),
  createdAt: timestamptz("created_at").notNull(),
});

export const uiComponentInterrupts = pgTable("ui_component_interrupts", {
  id: text("id").primaryKey(),
  uiInstanceId: text("ui_instance_id").notNull(),
  runId: text("run_id").notNull(),
  runStepId: text("run_step_id").notNull(),
  agentTurnId: text("agent_turn_id").notNull(),
  logicalThreadId: text("logical_thread_id").notNull(),
  toolCallId: text("tool_call_id").notNull(),
  sessionGenerationId: text("session_generation_id").notNull(),
  actionGrantId: text("action_grant_id").notNull(),
  inputSchemaHash: text("input_schema_hash").notNull(),
  state: text("state").notNull(),
  resultRedactedJson: jsonb("result_redacted_json"),
  resultHash: text("result_hash"),
  continuationQueueItemId: text("continuation_queue_item_id"),
  createdAt: timestamptz("created_at").notNull(),
  resolvedBy: text("resolved_by"),
  resolvedAt: timestamptz("resolved_at"),
  continuedAt: timestamptz("continued_at"),
  staleAt: timestamptz("stale_at"),
});

export const uiInteractions = pgTable("ui_interactions", {
  id: text("id").primaryKey(),
  uiInstanceId: text("ui_instance_id").notNull(),
  renderRevision: integer("render_revision").notNull(),
  expectedStateRevision: integer("expected_state_revision"),
  actionGrantId: text("action_grant_id").notNull(),
  renderNodeId: text("render_node_id").notNull(),
  handlerKey: text("handler_key").notNull(),
  intentName: text("intent_name").notNull(),
  payloadRedactedJson: jsonb("payload_redacted_json").notNull(),
  payloadHash: text("payload_hash").notNull(),
  interactionTokenHash: text("interaction_token_hash"),
  idempotencyKeyHash: text("idempotency_key_hash").notNull(),
  tokenExpiresAt: timestamptz("token_expires_at"),
  actorUserId: text("actor_user_id").notNull(),
  clientKind: text("client_kind").notNull(),
  state: text("state").notNull(),
  resultRedactedJson: jsonb("result_redacted_json"),
  resultRef: text("result_ref"),
  createdAt: timestamptz("created_at").notNull(),
  consumedAt: timestamptz("consumed_at"),
});

export const pauseGroups = pgTable("pause_groups", {
  id: text("id").primaryKey(),
  agentTurnId: text("agent_turn_id").notNull(),
  trueforgeTurnId: text("trueforge_turn_id").notNull(),
  generation: integer("generation").notNull(),
  state: text("state").notNull(),
  requiredActionCount: integer("required_action_count").notNull(),
  resolvedActionCount: integer("resolved_action_count").notNull(),
  resumeClaimToken: text("resume_claim_token"),
  createdAt: timestamptz("created_at").notNull(),
  readyAt: timestamptz("ready_at"),
  resumedAt: timestamptz("resumed_at"),
});

export const requiredActions = pgTable("required_actions", {
  id: text("id").primaryKey(),
  pauseGroupId: text("pause_group_id").notNull(),
  providerActionId: text("provider_action_id").notNull(),
  actionType: text("action_type").notNull(),
  state: text("state").notNull(),
  payloadRedactedJson: jsonb("payload_redacted_json").notNull(),
  payloadHash: text("payload_hash").notNull(),
  responseCiphertext: text("response_ciphertext"),
  responseRedactedJson: jsonb("response_redacted_json"),
  resolvedBy: text("resolved_by"),
  resolvedAt: timestamptz("resolved_at"),
  createdAt: timestamptz("created_at").notNull(),
});

export const pauseResumes = pgTable("pause_resumes", {
  id: text("id").primaryKey(),
  pauseGroupId: text("pause_group_id").notNull(),
  expectedGeneration: integer("expected_generation").notNull(),
  applicationRunToken: text("application_run_token").notNull(),
  responsePayloadHash: text("response_payload_hash").notNull(),
  responsePayloadCiphertext: text("response_payload_ciphertext").notNull(),
  state: text("state").notNull(),
  trueforgeResumeTurnId: text("trueforge_resume_turn_id"),
  claimedBy: text("claimed_by"),
  createdAt: timestamptz("created_at").notNull(),
  completedAt: timestamptz("completed_at"),
});

export const actionProposals = pgTable("action_proposals", {
  id: text("id").primaryKey(),
  requiredActionId: text("required_action_id").notNull(),
  runId: text("run_id").notNull(),
  runStepId: text("run_step_id").notNull(),
  agentTurnId: text("agent_turn_id").notNull(),
  threadId: text("thread_id"),
  toolCallId: text("tool_call_id").notNull(),
  sessionGenerationId: text("session_generation_id").notNull(),
  approvalPolicyHash: text("approval_policy_hash").notNull(),
  connectorBindingId: text("connector_binding_id").notNull(),
  toolName: text("tool_name").notNull(),
  observedDescriptorHash: text("observed_descriptor_hash").notNull(),
  actingIdentityJson: jsonb("acting_identity_json").notNull(),
  normalizedArgumentsRedactedJson: jsonb("normalized_arguments_redacted_json").notNull(),
  argumentsHash: text("arguments_hash").notNull(),
  targetRedactedJson: jsonb("target_redacted_json").notNull(),
  targetHash: text("target_hash").notNull(),
  artifactRevisionHash: text("artifact_revision_hash"),
  riskClass: text("risk_class").notNull(),
  expectedEffect: text("expected_effect").notNull(),
  state: text("state").notNull(),
  expiresAt: timestamptz("expires_at").notNull(),
  providerIdempotencyKey: text("provider_idempotency_key"),
  decidedBy: text("decided_by"),
  decisionReason: text("decision_reason"),
  decidedAt: timestamptz("decided_at"),
  executedAt: timestamptz("executed_at"),
  providerReceiptJson: jsonb("provider_receipt_json"),
});

export const questions = pgTable("questions", {
  id: text("id").primaryKey(),
  requiredActionId: text("required_action_id").notNull(),
  channelId: text("channel_id").notNull(),
  runId: text("run_id").notNull(),
  promptRedactedJson: jsonb("prompt_redacted_json").notNull(),
  promptHash: text("prompt_hash").notNull(),
  state: text("state").notNull(),
  answeredBy: text("answered_by"),
  answerCiphertext: text("answer_ciphertext"),
  answerRedactedJson: jsonb("answer_redacted_json"),
  answeredAt: timestamptz("answered_at"),
  expiresAt: timestamptz("expires_at").notNull(),
});

export const artifacts = pgTable("artifacts", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id").notNull(),
  runId: text("run_id").notNull(),
  runStepId: text("run_step_id").notNull(),
  creatorAgentId: text("creator_agent_id").notNull(),
  kind: text("kind").notNull(),
  name: text("name").notNull(),
  mimeType: text("mime_type").notNull(),
  storageKey: text("storage_key").notNull(),
  byteSize: integer("byte_size").notNull(),
  sha256: text("sha256").notNull(),
  sourceSandboxId: text("source_sandbox_id"),
  sourceSandboxPath: text("source_sandbox_path"),
  revision: integer("revision").notNull(),
  metadataJson: jsonb("metadata_json").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const auditEvents = pgTable("audit_events", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  channelId: text("channel_id"),
  actorType: text("actor_type").notNull(),
  actorId: text("actor_id").notNull(),
  action: text("action").notNull(),
  targetType: text("target_type").notNull(),
  targetId: text("target_id").notNull(),
  redactedPayloadJson: jsonb("redacted_payload_json").notNull(),
  payloadHash: text("payload_hash").notNull(),
  createdAt: timestamptz("created_at").notNull(),
});

export const schema = {
  users,
  workspaces,
  memberships,
  authSessions,
  agentProfiles,
  agentVersions,
  coworkerDrafts,
  sessionRevisions,
  skills,
  skillVersions,
  agentSkillBindings,
  channels,
  channelParticipants,
  channelEvents,
  messages,
  channelPins,
  tasks,
  taskRevisions,
  taskGrants,
  workspaceCommandReceipts,
  channelAgentSessions,
  channelAgentSessionGenerations,
  runs,
  runSteps,
  turnQueueItems,
  agentTurns,
  runEvents,
  aguiEventRecords,
  connectorBindings,
  toolGrants,
  uiComponents,
  uiComponentVersions,
  uiComponentGrants,
  uiDataFunctionGrants,
  uiInstances,
  uiInstanceRevisions,
  uiSurfaceGrants,
  uiComponentInterrupts,
  uiInteractions,
  pauseGroups,
  requiredActions,
  pauseResumes,
  actionProposals,
  questions,
  artifacts,
  auditEvents,
};

export const P0_TABLES = [
  "users",
  "workspaces",
  "memberships",
  "auth_sessions",
  "agent_profiles",
  "agent_versions",
  "coworker_drafts",
  "session_revisions",
  "skills",
  "skill_versions",
  "agent_skill_bindings",
  "channels",
  "channel_participants",
  "channel_events",
  "messages",
  "channel_pins",
  "tasks",
  "task_revisions",
  "task_grants",
  "workspace_command_receipts",
  "channel_agent_sessions",
  "channel_agent_session_generations",
  "runs",
  "run_steps",
  "turn_queue_items",
  "agent_turns",
  "run_events",
  "agui_event_records",
  "connector_bindings",
  "tool_grants",
  "ui_components",
  "ui_component_versions",
  "ui_component_grants",
  "ui_data_function_grants",
  "ui_instances",
  "ui_instance_revisions",
  "ui_surface_grants",
  "ui_component_interrupts",
  "ui_interactions",
  "pause_groups",
  "required_actions",
  "pause_resumes",
  "action_proposals",
  "questions",
  "artifacts",
  "audit_events",
] as const;
