-- Reverse of 0001_p0_foundation.sql. Drops P0 objects in dependency order.

DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS artifacts CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS action_proposals CASCADE;
DROP TABLE IF EXISTS pause_resumes CASCADE;
DROP TABLE IF EXISTS required_actions CASCADE;
DROP TABLE IF EXISTS pause_groups CASCADE;
DROP TABLE IF EXISTS ui_interactions CASCADE;
DROP TABLE IF EXISTS ui_component_interrupts CASCADE;
DROP TABLE IF EXISTS ui_surface_grants CASCADE;
DROP TABLE IF EXISTS ui_instance_revisions CASCADE;
DROP TABLE IF EXISTS ui_instances CASCADE;
DROP TABLE IF EXISTS ui_data_function_grants CASCADE;
DROP TABLE IF EXISTS ui_component_grants CASCADE;
DROP TABLE IF EXISTS ui_component_versions CASCADE;
DROP TABLE IF EXISTS ui_components CASCADE;
DROP TABLE IF EXISTS tool_grants CASCADE;
DROP TABLE IF EXISTS connector_bindings CASCADE;
DROP TABLE IF EXISTS agui_event_records CASCADE;
DROP TABLE IF EXISTS run_events CASCADE;
DROP TABLE IF EXISTS agent_turns CASCADE;
DROP TABLE IF EXISTS turn_queue_items CASCADE;
DROP TABLE IF EXISTS run_steps CASCADE;
DROP TABLE IF EXISTS channel_agent_session_generations CASCADE;
DROP TABLE IF EXISTS channel_agent_sessions CASCADE;
DROP TABLE IF EXISTS workspace_command_receipts CASCADE;
DROP TABLE IF EXISTS task_grants CASCADE;
DROP TABLE IF EXISTS task_revisions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS channel_pins CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS channel_events CASCADE;
DROP TABLE IF EXISTS channel_participants CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS agent_skill_bindings CASCADE;
DROP TABLE IF EXISTS skill_versions CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS session_revisions CASCADE;
DROP TABLE IF EXISTS coworker_drafts CASCADE;
DROP TABLE IF EXISTS agent_versions CASCADE;
DROP TABLE IF EXISTS agent_profiles CASCADE;
DROP TABLE IF EXISTS auth_sessions CASCADE;
DROP TABLE IF EXISTS memberships CASCADE;
DROP TABLE IF EXISTS workspaces CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS forgeroom_current_generation_is_live();
DROP FUNCTION IF EXISTS forgeroom_session_generations_protect_history();
DROP FUNCTION IF EXISTS forgeroom_coworker_drafts_protect_body();
DROP FUNCTION IF EXISTS forgeroom_forbid_mutation();
