#!/usr/bin/env bash
# Idempotent repository bootstrap for Cursor Cloud Agents.
# Installs the local PostgreSQL system dependency (Docker is unavailable in the
# default base image), installs workspace dependencies, and writes a local .env.
set -euo pipefail

cd "$(dirname "$0")/.."

# 1. System dependency: PostgreSQL 16 (only install when missing).
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  echo "[install] Installing PostgreSQL 16..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
else
  echo "[install] PostgreSQL already present; skipping apt install."
fi

# 2. Workspace dependencies (pinned via pnpm + lockfile).
echo "[install] Installing workspace dependencies..."
pnpm install --frozen-lockfile

# 3. Playwright browser for the @forgeroom/e2e suite (matches CI). The base
# image already carries the required system libraries.
echo "[install] Installing Playwright Chromium..."
pnpm --filter @forgeroom/e2e exec playwright install chromium

# 4. Local development .env (gitignored). Never used outside local dev.
if [ ! -f .env ]; then
  echo "[install] Writing local .env from development defaults..."
  cat > .env <<'ENV'
# Local development environment for ForgeRoom (generated by cloud-agent-install.sh).
# This file is gitignored. Never commit real secrets.
NODE_ENV=development
HOST=0.0.0.0
PORT=3000
FORGEROOM_EMBED_WORKER=true
APP_ORIGIN=http://localhost:5173
OWNER_USER_ID=user_owner
OWNER_EMAIL=owner@example.test
OWNER_DISPLAY_NAME=Owner
OWNER_PASSWORD=forgeroom-dev-password
OWNER_PASSWORD_HASH=
WORKSPACE_ID=workspace_1
WORKSPACE_NAME=ForgeRoom
WORKSPACE_SLUG=forgeroom
SESSION_COOKIE_NAME=fr_session
SESSION_TTL_SECONDS=43200
RECENT_AUTH_WINDOW_SECONDS=300
LOGIN_RATE_LIMIT_MAX=5
LOGIN_RATE_LIMIT_WINDOW_MS=60000
TRUST_PROXY=
AUTH_STORE=
DATABASE_URL=postgres://forgeroom:forgeroom@127.0.0.1:5432/forgeroom
PAUSE_PAYLOAD_ENCRYPTION_SECRET=
ARTIFACT_STORAGE_DIR=
TRUEFORGE_BASE_URL=http://127.0.0.1:8790
TRUEFORGE_API_KEY=
OPENAI_API_KEY=
MODEL_PROVIDER_API_KEY=
COMPOSIO_API_KEY=
COMPOSIO_CONNECTED_ACCOUNT_ID=
FORGEROOM_E2E_GITHUB_OWNER=
FORGEROOM_E2E_GITHUB_REPOSITORY=
COMPOSIO_USER_ID=
COMPOSIO_AUTH_CONFIG_ID=
DAYTONA_API_KEY=
ENV
else
  echo "[install] .env already exists; leaving it untouched."
fi

echo "[install] Done."
